# Generated by Django 6.1 on 2026-08-31 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
    ]
